[project]
name = "food-for-thought"
version = "0.1.0"
description = "A cooking game for typists."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.30.1",
    "pygame-ce>=2.5.5",
    "requests>=2.32.4",
]

[dependency-groups]
dev = [
    "ruff>=0.14.7",
]
